"""Integrity checks for the source registry and its generated status report.

Guards against the drift repaired in PR-A: the hand-maintained
reports/source_registry_status.csv had producer_script paths that disagreed with
registries/source_registry.json. The CSV is now generated by
scripts/gap_analysis_builder.write_status_csv; these tests keep it honest.
"""

import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from contract_sweeper.runtime.source_registry import (
    REPO_ROOT,
    all_sources,
    validate_registry,
)
from scripts.gap_analysis_builder import write_status_csv

STATUS_CSV = REPO_ROOT / "reports" / "source_registry_status.csv"


def _status_rows():
    with STATUS_CSV.open(encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def test_validate_registry_ok():
    report = validate_registry(REPO_ROOT)
    assert report["ok"], f"registry validation errors: {report['errors']}"
    assert report["errors"] == []


def test_status_csv_producer_scripts_match_registry():
    registry = {s["source_id"]: s["producer_script"] for s in all_sources(REPO_ROOT)}
    rows = _status_rows()
    assert {r["source_id"] for r in rows} == set(registry)
    for row in rows:
        assert row["producer_script"] == registry[row["source_id"]], (
            f"{row['source_id']}: status CSV producer_script "
            f"{row['producer_script']!r} != registry {registry[row['source_id']]!r}"
        )


def test_status_csv_regenerates_identically():
    """Verify that source_registry_status.csv is fully determined by the registry JSON.

    All columns (source_id, family, required, authentication, producer_script,
    expected_outputs, update_cadence, blocker_notes) derive exclusively from
    registries/source_registry.json — no filesystem presence check is involved.
    This means the file regenerates identically on any fresh clone without data
    files present.

    Note: pipeline_status is intentionally absent from this file. Live
    materialization state lives in reports/gap_analysis_report.csv, which is
    gitignored.
    """
    def _parse(path: Path) -> list[dict]:
        with path.open(encoding="utf-8", newline="") as f:
            return list(csv.DictReader(f))

    before = _parse(STATUS_CSV)
    write_status_csv(REPO_ROOT)
    after = _parse(STATUS_CSV)
    assert before == after, (
        "reports/source_registry_status.csv is stale — "
        "regenerate with: python3 scripts/gap_analysis_builder.py"
    )


def test_archived_producers_are_optional_only():
    for src in all_sources(REPO_ROOT):
        archived = str(src.get("producer_script", "")).startswith("archive/")
        if src.get("required"):
            assert not archived, (
                f"{src['source_id']}: required source must not point into archive/"
            )
