"""Fresh-clone reproducibility marker (Gate ``testing``, item ``fresh_clone_repro``).

Documents and guards the reproducibility CI job (``.github/workflows/repro.yml``)
that regenerates every top-form producer in a clean checkout and fails on any
diff. This test keeps the workflow and the producer set in sync: every top-form
``build_*`` producer that writes a committed artifact must be invoked by the job.
"""
from __future__ import annotations

import pytest

from scripts import build_entity_master as bem

REPO_ROOT = bem.REPO_ROOT
WORKFLOW = ".github/workflows/repro.yml"

# Every top-form producer whose output is committed and must be reproduced in CI.
REPRODUCED_PRODUCERS = [
    "scripts/build_entity_master.py",
    "scripts/build_agency_master.py",
    "scripts/build_person_master.py",
    "scripts/build_entity_aliases.py",
    "scripts/build_entity_parent_map.py",
    "scripts/build_entity_resolution_review_queue.py",
    "scripts/build_influence_edges.py",
    "scripts/build_debt_instruments.py",
    "scripts/build_creditor_mapping.py",
    "scripts/build_fiscal_control_events.py",
    "scripts/build_municipality_crosswalk.py",
    "scripts/build_geo_reason_codes.py",
    "scripts/build_hq_bias_reference.py",
    "scripts/build_gis_layer_manifest.py",
    "scripts/build_graph_export.py",
]


@pytest.fixture(scope="module")
def workflow_text() -> str:
    path = REPO_ROOT / WORKFLOW
    assert path.exists(), f"missing reproducibility workflow {WORKFLOW}"
    return path.read_text(encoding="utf-8")


@pytest.mark.unit
def test_workflow_invokes_every_top_form_producer(workflow_text):
    for producer in REPRODUCED_PRODUCERS:
        assert producer in workflow_text, f"{producer} not regenerated by {WORKFLOW}"


@pytest.mark.unit
def test_workflow_asserts_clean_tree(workflow_text):
    # the whole point: regenerate, then fail on any diff
    assert "git diff --exit-code" in workflow_text


@pytest.mark.unit
def test_every_reproduced_producer_exists():
    for producer in REPRODUCED_PRODUCERS:
        assert (REPO_ROOT / producer).exists(), f"missing producer {producer}"
