"""Integrity checks for the source registry and its generated status report.

Guards against the drift repaired in PR-A: the hand-maintained
reports/source_registry_status.csv had producer_script paths that disagreed with
registries/source_registry.json. The CSV is now generated by
scripts/gap_analysis_builder.write_status_csv; these tests keep it honest.
"""

import csv
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from contract_sweeper.runtime.source_registry import (
    REPO_ROOT,
    all_sources,
    validate_registry,
)
from scripts.gap_analysis_builder import write_status_csv

STATUS_CSV = REPO_ROOT / "reports" / "source_registry_status.csv"
STATUS_REL = "reports/source_registry_status.csv"


def _status_rows():
    with STATUS_CSV.open(encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def test_validate_registry_ok():
    report = validate_registry(REPO_ROOT)
    assert report["ok"], f"registry validation errors: {report['errors']}"
    assert report["errors"] == []


def test_status_csv_producer_scripts_match_registry():
    registry = {s["source_id"]: s["producer_script"] for s in all_sources(REPO_ROOT)}
    rows = _status_rows()
    assert {r["source_id"] for r in rows} == set(registry)
    for row in rows:
        assert row["producer_script"] == registry[row["source_id"]], (
            f"{row['source_id']}: status CSV producer_script "
            f"{row['producer_script']!r} != registry {registry[row['source_id']]!r}"
        )


def test_status_csv_regenerates_identically():
    """The committed status CSV must equal what the generator produces from a
    *clean* checkout.

    Regenerating against the live working tree is not order-independent: the
    status is data-presence derived (see gap_analysis_builder._source_status),
    so any test that leaves a transient output under data/staging/processed
    would flip a source's status and make this comparison flaky. Instead we
    regenerate inside a throwaway ``git worktree`` of HEAD — exactly the state a
    fresh CI checkout has — which is immune to working-tree pollution from other
    tests regardless of collection order.
    """
    committed = subprocess.run(
        ["git", "show", f"HEAD:{STATUS_REL}"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    with tempfile.TemporaryDirectory() as td:
        worktree = Path(td) / "wt"
        subprocess.run(
            ["git", "worktree", "add", "--detach", "-f", str(worktree), "HEAD"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
        try:
            write_status_csv(worktree)
            regenerated = (worktree / STATUS_REL).read_text(encoding="utf-8")
        finally:
            subprocess.run(
                ["git", "worktree", "remove", "--force", str(worktree)],
                cwd=REPO_ROOT,
                capture_output=True,
                text=True,
            )
    assert regenerated == committed, (
        "reports/source_registry_status.csv is stale — "
        "regenerate with: python3 scripts/gap_analysis_builder.py"
    )


def test_archived_producers_are_optional_only():
    for src in all_sources(REPO_ROOT):
        archived = str(src.get("producer_script", "")).startswith("archive/")
        if src.get("required"):
            assert not archived, f"{src['source_id']}: required source must not point into archive/"
