"""Install moneysweep-pr API keys from a `*_API_KEY.txt` zip into `.env`.

The zip is expected to contain one `<NAME>_API_KEY.txt` (or `_API_TOKEN.txt`)
file per key — each file holds the key value, possibly wrapped in whitespace
or smart quotes. Values are stripped and written into `<repo>/.env` with file
mode 0600 (which is gitignored — never committed).

Key NAMES (filename stems) are case-normalized to the canonical environment
variable names the producers read. Unrecognized stems are passed through
unchanged.

Usage:
    python3 scripts/install_api_keys_from_zip.py --zip /path/to/API_KEYS.zip
    python3 scripts/install_api_keys_from_zip.py --zip ... --force   # overwrite
    python3 scripts/install_api_keys_from_zip.py --zip ... --probe   # plus
                                                                       # auth probes

Key values are NEVER printed to stdout; only filenames, key NAMES, lengths,
and non-ASCII character counts are reported.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = REPO_ROOT / ".env"

# Filename stem (case-insensitive) -> canonical env var name.
# Producers read the canonical names; the map fixes common casing variants
# (e.g. "HigherGOV_API_KEY.txt" -> "HIGHERGOV_API_KEY").
NAME_NORMALIZATION = {
    "sam_api_key": "SAM_API_KEY",
    "highergov_api_key": "HIGHERGOV_API_KEY",
    "lda_api_key": "LDA_API_KEY",
    "fec_api_key": "FEC_API_KEY",
    "felt_api_key": "FELT_API_KEY",
    "nimble_api_key": "NIMBLE_API_KEY",
}

# Quote characters stripped from edges of each key value. Covers ASCII single
# and double quotes plus the smart-quote pairs commonly inserted by word
# processors and chat clients.
EDGE_QUOTE_CHARS = "\"'“”‘’′‵`"

# Filename of the canonical form (lowercased stem) must match this pattern.
_KEY_STEM_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_]*$")


def _normalize_name(stem: str) -> str:
    """Map a filename stem to its canonical env-var name."""
    lower = stem.lower()
    if lower in NAME_NORMALIZATION:
        return NAME_NORMALIZATION[lower]
    return stem.upper()


def _strip_edges(value: str) -> str:
    return value.strip().strip(EDGE_QUOTE_CHARS).strip()


def read_keys_from_zip(zip_path: Path) -> dict[str, str]:
    """Return {canonical_env_name: cleaned_value} from `*_API_KEY*.txt` entries."""
    keys: dict[str, str] = {}
    with zipfile.ZipFile(zip_path) as z:
        for name in z.namelist():
            if name.startswith("__MACOSX") or name.endswith("/"):
                continue
            base = os.path.basename(name)
            stem, ext = os.path.splitext(base)
            if ext.lower() != ".txt" or not _KEY_STEM_RE.match(stem):
                continue
            lower = stem.lower()
            if "api_key" not in lower and "api_token" not in lower:
                continue
            try:
                raw = z.read(name).decode("utf-8", errors="replace")
            except Exception:
                continue
            value = _strip_edges(raw)
            if value:
                keys[_normalize_name(stem)] = value
    return keys


def write_env(keys: dict[str, str], env_path: Path, force: bool) -> int:
    """Write `keys` into `env_path` (mode 0600). Returns number of keys written."""
    if env_path.exists() and not force:
        raise FileExistsError(f"{env_path} already exists. Re-run with --force to overwrite.")
    fd = os.open(str(env_path), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write("# Generated by scripts/install_api_keys_from_zip.py\n")
        f.write("# Gitignored. Never commit.\n")
        for k in sorted(keys):
            f.write(f"{k}={keys[k]}\n")
    return len(keys)


def diagnostics(keys: dict[str, str]) -> list[str]:
    """Return a list of safe per-key summary lines (no values)."""
    lines = []
    for k in sorted(keys):
        v = keys[k]
        non_ascii = sum(1 for c in v if ord(c) > 127)
        lines.append(f"  {k}: len={len(v)} non_ascii={non_ascii}")
    return lines


def _probe(label: str, url: str, headers: dict | None, key_to_redact: str | None):
    """Single authenticated GET; print only status + sanitized excerpt."""
    import urllib.error
    import urllib.request

    safe_url = url.replace(key_to_redact, "<REDACTED>") if key_to_redact else url
    print(f"  {label}: GET {safe_url[:140]}")
    try:
        req = urllib.request.Request(
            url,
            headers={"User-Agent": "moneysweep-pr-installer/0.1", **(headers or {})},
        )
        with urllib.request.urlopen(req, timeout=20) as resp:
            body = resp.read(400).decode("utf-8", errors="replace")
            if key_to_redact:
                body = body.replace(key_to_redact, "<REDACTED>")
            print(f"    status={resp.status}  result=key_works  body[:160]={body[:160]!r}")
    except urllib.error.HTTPError as e:
        try:
            body = e.read().decode("utf-8", errors="replace")
        except Exception:
            body = ""
        if key_to_redact:
            body = body.replace(key_to_redact, "<REDACTED>")
        if "not in allowlist" in body.lower():
            r = "host_blocked"
        elif e.code in (401, 403):
            r = "key_invalid_or_unauthorized"
        else:
            r = f"http_{e.code}"
        print(f"    status={e.code}  result={r}  body[:160]={body[:160]!r}")
    except Exception as e:
        print(f"    transport_error: {type(e).__name__}: {str(e)[:120]}")


def probe_keys(keys: dict[str, str]) -> None:
    """Optional auth probes for the keys producers actually use over the wire."""
    print("\nProbing endpoints (key values redacted)...")
    sam = keys.get("SAM_API_KEY")
    if sam:
        import urllib.parse

        url = "https://api.sam.gov/entity-information/v3/entities?" + urllib.parse.urlencode(
            {"api_key": sam, "samRegistered": "Yes", "page": "0", "size": "1"}
        )
        _probe("sam_entities", url, None, sam)
    hg = keys.get("HIGHERGOV_API_KEY")
    if hg:
        _probe(
            "highergov_contract",
            f"https://www.highergov.com/api-external/contract/?api_key={hg}&page_size=1",
            None,
            hg,
        )
    lda = keys.get("LDA_API_KEY")
    if lda:
        _probe(
            "lda_filings",
            "https://lda.senate.gov/api/v1/filings/?page_size=1",
            {"Authorization": f"Token {lda}"},
            lda,
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--zip", required=True, type=Path, help="Path to the API_KEYS.zip")
    parser.add_argument("--env", type=Path, default=ENV_PATH, help="Output .env path")
    parser.add_argument("--force", action="store_true", help="Overwrite existing .env")
    parser.add_argument("--probe", action="store_true", help="Run auth probes after install")
    args = parser.parse_args(argv)

    if not args.zip.exists():
        print(f"error: zip not found at {args.zip}", file=sys.stderr)
        return 2

    keys = read_keys_from_zip(args.zip)
    if not keys:
        print("error: zip contained no recognizable *_API_KEY.txt entries", file=sys.stderr)
        return 3

    print(f"Found {len(keys)} key(s) in {args.zip.name}:")
    for line in diagnostics(keys):
        print(line)

    try:
        n = write_env(keys, args.env, args.force)
    except FileExistsError as e:
        print(f"error: {e}", file=sys.stderr)
        return 4

    mode = oct(args.env.stat().st_mode & 0o777)
    print(f"\nWrote {n} key(s) to {args.env} (mode {mode}, {args.env.stat().st_size} bytes)")

    if args.probe:
        probe_keys(keys)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
